name: WebRtcNativeWindows

on: workflow_dispatch

env:
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  
jobs:
  build:
    runs-on: windows-latest
     
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1  
      with:
        msbuild-architecture: x64
    - name: VS C++ MFC/ATL support 
      run: &'C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe' --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended
    
