name: WebRtcNativeWindows

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download and extract 'depot_tools'
      uses: gamedev-thingy/Download-Extract@v2
        with:
          url: "https://storage.googleapis.com/chrome-infra/depot_tools.zip"
          destination: ./depot_tools
          ZIPname: depot_tools.zip
      - name: dir
        shell: cmd
        run: dir    
    
