name: WebRtcNativeWindows

on: workflow_dispatch

env:
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  
jobs:
  build:
    runs-on: windows-latest
     
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1  
      with:
        msbuild-architecture: x64
    - name: VS C++ MFC/ATL support 
      run: winget install --id Microsoft.VisualStudio.2022.Enterprise "--quiet --add Microsoft.VisualStudio.Workload.NativeDesktop"
    
