name: WebRtcNativeWindows

on: workflow_dispatch

env:
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  GYP_GENERATORS: msvs-ninja,ninja
  GYP_MSVS_OVERRIDE_PATH: C:\"Program Files"\"Microsoft Visual Studio"\2022\Enterprise
  GYP_MSVS_VERSION: 2022  
  
jobs:
  build:
    runs-on: windows-latest
     
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1  
      with:
        msbuild-architecture: x64
    - name: VS C++ MFC/ATL support 
      run: C:\"Program Files (x86)"\"Microsoft Visual Studio"\Installer\setup.exe modify --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended --downloadThenInstall --quiet
    
    - name: Create 'depot_tools' folder
      run: mkdir .\depot_tools
    - name: Download and extract 'depot_tools'
      uses: gamedev-thingy/Download-Extract@v2
      with:
        url: "https://storage.googleapis.com/chrome-infra/depot_tools.zip"
        destination: .\depot_tools
        ZIPname: depot_tools
    - name: Export 'depot_tools' path
      run: Add-Content $env:GITHUB_PATH $env:GITHUB_WORKSPACE\depot_tools
    - name: Execute 'gclient'
      shell: cmd
      run: gclient
    - name: set
      run: |
        dir env:
    - name: Check 'python'
      shell: cmd
      run: where python
    
