name: WebRtcNativeWindows

on: [workflow_dispatch]
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checking...
      run: |
        dir
        echo $GITHUB_WORKSPACE
        echo $env:GITHUB_WORKSPACE
    - name: Create 'depot_tools' folder
      run: mkdir .\depot_tools
    ##- name: Download and extract 'depot_tools'
      ##uses: gamedev-thingy/Download-Extract@v2
      ##with:
        ##url: "https://storage.googleapis.com/chrome-infra/depot_tools.zip"
        ##destination: .\depot_tools
        ##ZIPname: depot_tools
    - name: dir
      shell: cmd
      run: dir 
    - name: Export 'depot_tools' path
      shell: cmd
      run: |
        set PATH=$GITHUB_WORKSPACE\depot_tools; %PATH%
        set
    - name: Execute 'gclient'
      shell: cmd
      run: gclient
    - name: Check 'python'
      shell: cmd
      run: where python
    
