## !!!IMPORTANT!!! Using C: drive as default D: has only 14BG available space

name: WebRtcNativeWindows

on: workflow_dispatch

env:
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  GYP_GENERATORS: msvs-ninja,ninja
  GYP_MSVS_OVERRIDE_PATH: C:\"Program Files"\"Microsoft Visual Studio"\2022\Enterprise
  vs2022_install: C:\"Program Files"\"Microsoft Visual Studio"\2022\Enterprise
  GYP_MSVS_VERSION: 2022
  PYTHON_BIN_ABSDIR: C:\hostedtoolcache\windows\Python\3.9.13\x64
  
jobs:
  build:
    runs-on: windows-latest
     
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1  
      with:
        msbuild-architecture: x64
##    - name: VS C++ MFC/ATL support 
##      run: C:\"Program Files (x86)"\"Microsoft Visual Studio"\Installer\setup.exe modify --add Microsoft.VisualStudio.Component.VC.ATLMFC --includeRecommended --downloadThenInstall --quiet
    
    - name: Create 'depot_tools' folder
      run: |
        c:
        mkdir \depot_tools
        cd \depot_tools
        Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile .\depot_tools.zip
        7z x -y depot_tools.zip
        del depot_tools.zip
        c:
    - name: Export 'depot_tools' path
      run: Add-Content $env:GITHUB_PATH c:\depot_tools
    - name: Execute 'gclient'
      run: gclient
    
    - name: Configure Git
      run: |
        git config --global user.name "melihercan"
        git config --global user.email "melihercan@gmail.com"
        git config --global core.autocrlf false
        git config --global core.filemode false
        git config --global branch.autosetuprebase always
        
    - name: Get-Volume
      run: Get-Volume        
        
    - name: Get the code
      run: |
        c:
        mkdir webrtc-checkout
        cd webrtc-checkout
        fetch --nohooks webrtc
        gclient sync
        cd src
        git checkout branch-heads/5481
        
    - name: Generate Ninja project and build
      run: |
        cd c:\webrtc-checkout\src
        gn gen out/Default --args='is_debug=false'
        autoninja all -C out/Default
        
    
