name: WebRtcNativeWindows

on: workflow_dispatch
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Create 'depot_tools' folder
      run: mkdir .\depot_tools
    - name: Download and extract 'depot_tools'
      uses: gamedev-thingy/Download-Extract@v2
      with:
        url: "https://storage.googleapis.com/chrome-infra/depot_tools.zip"
        destination: .\depot_tools
        ZIPname: depot_tools
    - name: Export 'depot_tools' path
      run: Add-Content $env:GITHUB_PATH $env:GITHUB_WORKSPACE\depot_tools
    - name: Execute 'gclient'
      run: |
        [Environment]::SetEnvironmentVariable('DEPOT_TOOLS_UPDATE', '1', 'Machine')
        gclient
    - name: set
      shell: cmd
      run: set
    - name: Check 'python'
      shell: cmd
      run: where python
    
