name: WebRtcNativeWindows

on: workflow_dispatch
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checking...
      run: |
        echo $env:GITHUB_WORKSPACE
        dir env:
    - name: Create 'depot_tools' folder
      run: mkdir .\depot_tools
    #- name: Download and extract 'depot_tools'
      #uses: gamedev-thingy/Download-Extract@v2
      #with:
        #url: "https://storage.googleapis.com/chrome-infra/depot_tools.zip"
        #destination: .\depot_tools
        #ZIPname: depot_tools
    - name: dir
      run: dir .\depot_tools 
    - name: Export 'depot_tools' path
      run: Add-Content $env:GITHUB_PATH $env:GITHUB_WORKSPACE\depot_tools
    - name: echo
      run: dir env:
    - name: Execute 'gclient'
      run: gclient
    - name: Check 'python'
      run: where python
    
